<?php

namespace LasVenturas\BlackjackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GamesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GamesRepository extends EntityRepository
{
}
