<?php

namespace LasVenturas\BlackjackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function getTopPlayers()
    {
    	$userRepository = $this->getEntityManager()->getRepository('LasVenturasBlackjackBundle:User');
        $topPlayers = $userRepository->findBy(array(), array('wallet' => 'DESC'),5);
        // echo '<pre>'; print_r($topPlayers); echo '</pre>';  
        return $topPlayers; 
    }
}
