las_venturas_blackjack_homepage:
    path:     /
    defaults: { _controller: LasVenturasBlackjackBundle:Home:index }

las_venturas_blackjack_pregame:
    path:     /pregame
    defaults: { _controller: LasVenturasBlackjackBundle:PreGame:index}

las_venturas_blackjack_game:
    path:     /game
    defaults: { _controller: LasVenturasBlackjackBundle:Game:index}

las_venturas_blackjack_stats:
    path:     /stats
    defaults: { _controller: LasVenturasBlackjackBundle:Stats:index }

las_venturas_blackjack_user:
    path:     /user
    defaults: { _controller: LasVenturasBlackjackBundle:User:index }