las_venturas_blackjack_homepage:
    path:     /
    defaults: { _controller: LasVenturasBlackjackBundle:Home:index }

las_venturas_blackjack_game:
    path:     /game
    defaults: { _controller: LasVenturasBlackjackBundle:Game:index}

las_venturas_blackjack_hitme:
    path:     /hitme/{userName}/{roundId}/{playerScore}
    defaults: { _controller: LasVenturasBlackjackBundle:Game:hitMe}

las_venturas_blackjack_finish:
    path:     /finish/{userName}/{roundId}/{playerScore}
    defaults: { _controller: LasVenturasBlackjackBundle:Game:finish}

las_venturas_blackjack_stats:
    path:     /stats
    defaults: { _controller: LasVenturasBlackjackBundle:Stats:index }

las_venturas_blackjack_userProfile:
    path:     /stats/{userName}
    defaults: { _controller: LasVenturasBlackjackBundle:Stats:showUserStats }

las_venturas_blackjack_user:
    path:     /user
    defaults: { _controller: LasVenturasBlackjackBundle:User:index }